// Mocks generated by Mockito 5.4.4 from annotations
// in dual_reader/test/src/data/services/book_language_detection_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dual_reader/src/data/services/language_detection_service.dart'
    as _i2;
import 'package:dual_reader/src/domain/entities/book_entity.dart' as _i5;
import 'package:dual_reader/src/domain/repositories/book_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLanguageDetectionResult_0 extends _i1.SmartFake
    implements _i2.LanguageDetectionResult {
  _FakeLanguageDetectionResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BookRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBookRepository extends _i1.Mock implements _i3.BookRepository {
  MockBookRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.BookEntity>> getAllBooks() => (super.noSuchMethod(
        Invocation.method(
          #getAllBooks,
          [],
        ),
        returnValue: _i4.Future<List<_i5.BookEntity>>.value(<_i5.BookEntity>[]),
      ) as _i4.Future<List<_i5.BookEntity>>);

  @override
  _i4.Future<_i5.BookEntity?> getBookById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getBookById,
          [id],
        ),
        returnValue: _i4.Future<_i5.BookEntity?>.value(),
      ) as _i4.Future<_i5.BookEntity?>);

  @override
  _i4.Future<void> addBook(_i5.BookEntity? book) => (super.noSuchMethod(
        Invocation.method(
          #addBook,
          [book],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateBook(_i5.BookEntity? book) => (super.noSuchMethod(
        Invocation.method(
          #updateBook,
          [book],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteBook(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteBook,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> saveBookBytes(
    String? id,
    List<int>? bytes,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveBookBytes,
          [
            id,
            bytes,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<int>?> getBookBytes(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getBookBytes,
          [id],
        ),
        returnValue: _i4.Future<List<int>?>.value(),
      ) as _i4.Future<List<int>?>);
}

/// A class which mocks [LanguageDetectionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLanguageDetectionService extends _i1.Mock
    implements _i2.LanguageDetectionService {
  MockLanguageDetectionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  int get minConfidence => (super.noSuchMethod(
        Invocation.getter(#minConfidence),
        returnValue: 0,
      ) as int);

  @override
  _i4.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void setMinConfidence(int? confidence) => super.noSuchMethod(
        Invocation.method(
          #setMinConfidence,
          [confidence],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<_i2.LanguageDetectionResult> detectWithConfidence(String? text) =>
      (super.noSuchMethod(
        Invocation.method(
          #detectWithConfidence,
          [text],
        ),
        returnValue: _i4.Future<_i2.LanguageDetectionResult>.value(
            _FakeLanguageDetectionResult_0(
          this,
          Invocation.method(
            #detectWithConfidence,
            [text],
          ),
        )),
      ) as _i4.Future<_i2.LanguageDetectionResult>);

  @override
  _i4.Future<String> detectLanguage(String? text) => (super.noSuchMethod(
        Invocation.method(
          #detectLanguage,
          [text],
        ),
        returnValue: _i4.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #detectLanguage,
            [text],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<List<_i2.MixedLanguageResult>> detectMixedLanguages(
          String? text) =>
      (super.noSuchMethod(
        Invocation.method(
          #detectMixedLanguages,
          [text],
        ),
        returnValue: _i4.Future<List<_i2.MixedLanguageResult>>.value(
            <_i2.MixedLanguageResult>[]),
      ) as _i4.Future<List<_i2.MixedLanguageResult>>);

  @override
  _i4.Future<void> clearCache() => (super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  Map<String, dynamic> getCacheStats() => (super.noSuchMethod(
        Invocation.method(
          #getCacheStats,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i4.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
