// Mocks generated by Mockito 5.4.4 from annotations
// in dual_reader/test/src/data/services/chunk_translation_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:dual_reader/src/data/services/chunk_cache_service.dart' as _i2;
import 'package:dual_reader/src/data/services/client_side_translation_service.dart'
    as _i5;
import 'package:dual_reader/src/domain/entities/translation_chunk.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ChunkCacheService].
///
/// See the documentation for Mockito's code generation for more information.
class MockChunkCacheService extends _i1.Mock implements _i2.ChunkCacheService {
  MockChunkCacheService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> cacheChunk(_i4.TranslationChunk? chunk) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheChunk,
          [chunk],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i4.TranslationChunk? getCachedChunk(String? chunkId) =>
      (super.noSuchMethod(Invocation.method(
        #getCachedChunk,
        [chunkId],
      )) as _i4.TranslationChunk?);

  @override
  _i4.TranslationChunk? getCachedChunkForPage(
    String? bookId,
    int? pageIndex,
    String? language,
  ) =>
      (super.noSuchMethod(Invocation.method(
        #getCachedChunkForPage,
        [
          bookId,
          pageIndex,
          language,
        ],
      )) as _i4.TranslationChunk?);

  @override
  bool isPageCached(
    String? bookId,
    int? pageIndex,
    String? language,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #isPageCached,
          [
            bookId,
            pageIndex,
            language,
          ],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i3.Future<void> clearBook(String? bookId) => (super.noSuchMethod(
        Invocation.method(
          #clearBook,
          [bookId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> clearBookLanguage(
    String? bookId,
    String? language,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearBookLanguage,
          [
            bookId,
            language,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> clearAll() => (super.noSuchMethod(
        Invocation.method(
          #clearAll,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<Map<String, dynamic>> getStats() => (super.noSuchMethod(
        Invocation.method(
          #getStats,
          [],
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);
}

/// A class which mocks [ClientSideTranslationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockClientSideTranslationService extends _i1.Mock
    implements _i5.ClientSideTranslationService {
  MockClientSideTranslationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> translate({
    required String? text,
    required String? targetLanguage,
    String? sourceLanguage,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #translate,
          [],
          {
            #text: text,
            #targetLanguage: targetLanguage,
            #sourceLanguage: sourceLanguage,
          },
        ),
        returnValue: _i3.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #translate,
            [],
            {
              #text: text,
              #targetLanguage: targetLanguage,
              #sourceLanguage: sourceLanguage,
            },
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<String> detectLanguage(String? text) => (super.noSuchMethod(
        Invocation.method(
          #detectLanguage,
          [text],
        ),
        returnValue: _i3.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #detectLanguage,
            [text],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> isLanguageModelReady(String? languageCode) =>
      (super.noSuchMethod(
        Invocation.method(
          #isLanguageModelReady,
          [languageCode],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> downloadLanguageModel(
    String? languageCode, {
    void Function(String)? onProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadLanguageModel,
          [languageCode],
          {#onProgress: onProgress},
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}
