// Mocks generated by Mockito 5.4.4 from annotations
// in dual_reader/test/src/data/services/client_side_translation_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:dual_reader/src/data/services/client_side_translation_service.dart'
    as _i4;
import 'package:dual_reader/src/data/services/translation_cache_service.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [TranslationCacheService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTranslationCacheService extends _i1.Mock
    implements _i2.TranslationCacheService {
  MockTranslationCacheService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> cacheTranslation(
    String? originalText,
    String? targetLanguage,
    String? translatedText,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheTranslation,
          [
            originalText,
            targetLanguage,
            translatedText,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  String? getCachedTranslation(
    String? originalText,
    String? targetLanguage,
  ) =>
      (super.noSuchMethod(Invocation.method(
        #getCachedTranslation,
        [
          originalText,
          targetLanguage,
        ],
      )) as String?);
}

/// A class which mocks [ClientSideTranslationDelegate].
///
/// See the documentation for Mockito's code generation for more information.
class MockClientSideTranslationDelegate extends _i1.Mock
    implements _i4.ClientSideTranslationDelegate {
  MockClientSideTranslationDelegate() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> translate({
    required String? text,
    required String? targetLanguage,
    String? sourceLanguage,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #translate,
          [],
          {
            #text: text,
            #targetLanguage: targetLanguage,
            #sourceLanguage: sourceLanguage,
          },
        ),
        returnValue: _i3.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #translate,
            [],
            {
              #text: text,
              #targetLanguage: targetLanguage,
              #sourceLanguage: sourceLanguage,
            },
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<String> detectLanguage(String? text) => (super.noSuchMethod(
        Invocation.method(
          #detectLanguage,
          [text],
        ),
        returnValue: _i3.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #detectLanguage,
            [text],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> isLanguageModelReady(String? languageCode) =>
      (super.noSuchMethod(
        Invocation.method(
          #isLanguageModelReady,
          [languageCode],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> downloadLanguageModel(
    String? languageCode, {
    void Function(String)? onProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadLanguageModel,
          [languageCode],
          {#onProgress: onProgress},
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}
