import 'dart:io';

/// Verification script for Web Platform Settings Configuration
/// Run with: dart run web/verify_web_platform_configuration.dart

void main() {
  print('=' * 70);
  print('Web Platform Settings Configuration Verification');
  print('Dual Reader 3.1');
  print('=' * 70);
  print('');

  final successes = <String>[];
  final warnings = <String>[];
  final errors = <String>[];

  // 1. Check manifest.json
  print('1. Checking PWA manifest.json...');
  final manifestFile = File('web/manifest.json');
  if (manifestFile.existsSync()) {
    final manifestContent = manifestFile.readAsStringSync();
    
    // Check required fields
    final requiredFields = [
      'name',
      'short_name',
      'start_url',
      'display',
      'icons',
      'theme_color',
      'background_color',
    ];
    
    bool allFieldsPresent = true;
    for (final field in requiredFields) {
      if (!manifestContent.contains('"$field"')) {
        errors.add('manifest.json missing required field: $field');
        allFieldsPresent = false;
      }
    }
    
    if (allFieldsPresent) {
      successes.add('manifest.json exists with all required fields');
      print('   ✅ manifest.json exists with all required fields');
    } else {
      print('   ❌ manifest.json missing required fields');
    }
    
    // Check for PWA features
    if (manifestContent.contains('"shortcuts"')) {
      successes.add('manifest.json includes shortcuts');
      print('   ✅ Includes shortcuts');
    }
    if (manifestContent.contains('"share_target"')) {
      successes.add('manifest.json includes share_target');
      print('   ✅ Includes share_target');
    }
  } else {
    errors.add('manifest.json not found');
    print('   ❌ manifest.json not found');
  }

  // 2. Check index.html
  print('');
  print('2. Checking index.html...');
  final indexFile = File('web/index.html');
  if (indexFile.existsSync()) {
    final indexContent = indexFile.readAsStringSync();
    
    // Check for manifest link
    if (indexContent.contains('manifest.json')) {
      successes.add('index.html links to manifest.json');
      print('   ✅ Links to manifest.json');
    } else {
      errors.add('index.html missing manifest.json link');
      print('   ❌ Missing manifest.json link');
    }
    
    // Check for responsive meta tags
    final metaTags = [
      'viewport',
      'theme-color',
      'apple-mobile-web-app-capable',
      'mobile-web-app-capable',
    ];
    
    int metaTagsFound = 0;
    for (final tag in metaTags) {
      if (indexContent.contains(tag)) {
        metaTagsFound++;
      }
    }
    
    if (metaTagsFound == metaTags.length) {
      successes.add('index.html includes responsive meta tags');
      print('   ✅ Includes responsive meta tags');
    } else {
      warnings.add('index.html missing some responsive meta tags');
      print('   ⚠️  Some responsive meta tags may be missing');
    }
    
    // Check for service worker reference
    if (indexContent.contains('serviceWorker') || 
        indexContent.contains('flutter_service_worker')) {
      successes.add('index.html references service worker');
      print('   ✅ References service worker');
    }
  } else {
    errors.add('index.html not found');
    print('   ❌ index.html not found');
  }

  // 3. Check service worker configuration
  print('');
  print('3. Checking service worker configuration...');
  print('   ℹ️  Flutter automatically generates flutter_service_worker.js during build');
  successes.add('Service worker will be auto-generated by Flutter');
  print('   ✅ Service worker will be auto-generated by Flutter');
  
  // Check for custom service worker (optional)
  final customSwFile = File('web/service-worker.js');
  if (customSwFile.existsSync()) {
    warnings.add('Custom service-worker.js exists (Flutter uses flutter_service_worker.js)');
    print('   ℹ️  Custom service-worker.js exists (Flutter uses flutter_service_worker.js)');
  }

  // 4. Check icons
  print('');
  print('4. Checking PWA icons...');
  final iconSizes = [16, 32, 72, 96, 128, 144, 152, 192, 384, 512];
  int iconsFound = 0;
  
  for (final size in iconSizes) {
    final iconFile = File('web/icons/icon-${size}x${size}.png');
    if (iconFile.existsSync()) {
      iconsFound++;
    }
  }
  
  if (iconsFound == iconSizes.length) {
    successes.add('All PWA icons exist');
    print('   ✅ All PWA icons exist ($iconsFound/${iconSizes.length})');
  } else if (iconsFound > 0) {
    warnings.add('Some PWA icons missing ($iconsFound/${iconSizes.length})');
    print('   ⚠️  Some PWA icons missing ($iconsFound/${iconSizes.length})');
    print('      Run: dart run web/create_icons.ps1 or use web/icons/generate_icons_simple.html');
  } else {
    warnings.add('PWA icons not found');
    print('   ⚠️  PWA icons not found');
    print('      Run: dart run web/create_icons.ps1 or use web/icons/generate_icons_simple.html');
  }
  
  // Check favicon
  final faviconFile = File('web/favicon.png');
  if (faviconFile.existsSync()) {
    successes.add('Favicon exists');
    print('   ✅ Favicon exists');
  } else {
    warnings.add('Favicon not found');
    print('   ⚠️  Favicon not found');
  }

  // 5. Check web configuration files
  print('');
  print('5. Checking web configuration files...');
  
  final configFiles = {
    'flutter_build_config.json': 'Flutter build configuration',
    '_headers': 'Netlify headers configuration',
    '.htaccess': 'Apache server configuration',
    'vercel.json': 'Vercel deployment configuration',
    'browserconfig.xml': 'Windows tile configuration',
  };
  
  for (final entry in configFiles.entries) {
    final file = File('web/${entry.key}');
    if (file.existsSync()) {
      successes.add('${entry.value} exists');
      print('   ✅ ${entry.value}');
    } else {
      warnings.add('${entry.value} not found');
      print('   ⚠️  ${entry.value} not found');
    }
  }

  // 6. Summary
  print('');
  print('=' * 70);
  print('Verification Summary');
  print('=' * 70);
  print('');
  print('✅ Successes: ${successes.length}');
  print('⚠️  Warnings: ${warnings.length}');
  print('❌ Errors: ${errors.length}');
  print('');
  
  if (errors.isNotEmpty) {
    print('Errors:');
    for (final error in errors) {
      print('  ❌ $error');
    }
    print('');
  }
  
  if (warnings.isNotEmpty) {
    print('Warnings:');
    for (final warning in warnings) {
      print('  ⚠️  $warning');
    }
    print('');
  }
  
  if (errors.isEmpty && warnings.isEmpty) {
    print('🎉 All checks passed! Web platform settings are fully configured.');
  } else if (errors.isEmpty) {
    print('✅ Core configuration complete. Some optional items need attention.');
  } else {
    print('❌ Configuration incomplete. Please fix errors above.');
  }
  
  print('');
  print('Next Steps:');
  print('  1. Generate icons if missing:');
  print('     - PowerShell: .\\web\\create_icons.ps1');
  print('     - Browser: Open web/icons/generate_icons_simple.html');
  print('  2. Build web app: flutter build web --release');
  print('  3. Test PWA: flutter run -d chrome');
  print('  4. Verify installability in Chrome DevTools > Application > Manifest');
  print('');
}
