#!/usr/bin/env bash
# Batched test runner for OOM mitigation
# Problem: MockK/Kotlin reflection generates ~100+ MB metaspace per test class
#          running all classes in one JVM exceeds metaspace limits
# Solution: Split into batches with a fresh JVM per batch (auto-generated batches)
#
# Auto-generated by regenerate-test-batches.py from the test directory listing.
# Re-run that script after adding/removing test classes.

set -e
cd "$(dirname "$0")"

export JAVA_HOME="/c/Users/Svetlin/.jdks/temurin-21/jdk-21.0.11+10"
export TMPDIR="/tmp"

# Kill stale daemons holding file locks before starting
taskkill //F //IM java.exe 2>/dev/null || true
sleep 3

echo "========================================="
echo "Running full unit test suite in batches"
echo "========================================="

PASSED=0
FAILED=0
BATCHES_FAILED=0
BATCH_IDX=0

run_batch() {
    BATCH_IDX=$((BATCH_IDX+1))
    local count=$1; shift
    echo ""
    echo "[Batch $BATCH_IDX] $count test class(es)"
    echo "----------------------------"
    if timeout 900 ./gradlew :app:testDebugUnitTest --no-daemon \
        -Djava.io.tmpdir="$TMPDIR" \
        "$@"; then
        PASSED=$((PASSED+1))
    else
        FAILED=$((FAILED+1))
        BATCHES_FAILED=$((BATCHES_FAILED+1))
    fi
}

# Each batch: fresh JVM, bounded class count (OOM mitigation)
run_batch 8 \
    --tests "com.dualreader.app.data.local.ConvertersTest" \
    --tests "com.dualreader.app.data.local.mapper.MappersTest" \
    --tests "com.dualreader.app.data.local.mapper.ProgressMappingTest" \
    --tests "com.dualreader.app.data.pagination.PaginationIntegrationTest" \
    --tests "com.dualreader.app.data.pagination.SentenceBoundaryTest" \
    --tests "com.dualreader.app.data.parser.EpubParserImplCancellationTest" \
    --tests "com.dualreader.app.data.parser.EpubParserImplTest" \
    --tests "com.dualreader.app.data.parser.EpubParserSplitTest"

run_batch 8 \
    --tests "com.dualreader.app.data.parser.SentenceSplitterTest" \
    --tests "com.dualreader.app.data.parser.TomSawyerParagraphTest" \
    --tests "com.dualreader.app.data.repository.BillingRepositoryCleanupTest" \
    --tests "com.dualreader.app.data.repository.BookmarkRepositoryImplTest" \
    --tests "com.dualreader.app.data.repository.BookRepositoryImplTest" \
    --tests "com.dualreader.app.data.repository.LibraryRepositoryCollectionValidationTest" \
    --tests "com.dualreader.app.data.repository.LibraryRepositoryImplTest" \
    --tests "com.dualreader.app.data.repository.LibraryRepositoryTagValidationTest"

run_batch 8 \
    --tests "com.dualreader.app.data.repository.SettingsRepositoryImplTest" \
    --tests "com.dualreader.app.data.repository.TranslationCacheRepositoryImplDR203Test" \
    --tests "com.dualreader.app.data.repository.TranslationCacheRepositoryImplTest" \
    --tests "com.dualreader.app.data.translation.CloudTranslationResilienceTest" \
    --tests "com.dualreader.app.data.translation.CloudTranslationServiceImplAdditionalTest" \
    --tests "com.dualreader.app.data.translation.CloudTranslationServiceImplTest" \
    --tests "com.dualreader.app.data.translation.FallbackTranslationServiceCallbackTest" \
    --tests "com.dualreader.app.data.translation.FallbackTranslationServicePagesTest"

run_batch 8 \
    --tests "com.dualreader.app.data.translation.FallbackTranslationServicePartialFailureTest" \
    --tests "com.dualreader.app.data.translation.FallbackTranslationServiceTest" \
    --tests "com.dualreader.app.data.translation.InstallationIdProviderDR206Test" \
    --tests "com.dualreader.app.data.translation.InstallationIdProviderTest" \
    --tests "com.dualreader.app.data.translation.LocalFirstTranslationTest" \
    --tests "com.dualreader.app.data.translation.ParagraphAlignerTest" \
    --tests "com.dualreader.app.data.translation.ParagraphMarkerArtifactTest" \
    --tests "com.dualreader.app.data.translation.QuotaResponseTest"

run_batch 8 \
    --tests "com.dualreader.app.data.tts.LocaleMapperTest" \
    --tests "com.dualreader.app.data.tts.TtsServiceImplCancellationTest" \
    --tests "com.dualreader.app.data.tts.TtsServiceImplThreadSafetyTest" \
    --tests "com.dualreader.app.domain.entities.BookTest" \
    --tests "com.dualreader.app.domain.entities.DisplayModeTest" \
    --tests "com.dualreader.app.domain.entities.LibraryEntitiesTest" \
    --tests "com.dualreader.app.domain.entities.PageTest" \
    --tests "com.dualreader.app.domain.entities.ReadingSettingsTest"

run_batch 8 \
    --tests "com.dualreader.app.domain.export.BookmarkExporterDR205Test" \
    --tests "com.dualreader.app.domain.export.BookmarkExporterTest" \
    --tests "com.dualreader.app.domain.model.EntitlementTierTest" \
    --tests "com.dualreader.app.domain.model.ProductInfoTest" \
    --tests "com.dualreader.app.domain.model.PurchaseResultTest" \
    --tests "com.dualreader.app.domain.services.TranslationServiceTypesTest" \
    --tests "com.dualreader.app.domain.usecases.BookContextExtractorTest" \
    --tests "com.dualreader.app.domain.usecases.ImportBookUseCaseTest"

run_batch 8 \
    --tests "com.dualreader.app.domain.usecases.PaginateBookUseCaseDR207Test" \
    --tests "com.dualreader.app.domain.usecases.PaginateBookUseCaseTest" \
    --tests "com.dualreader.app.domain.usecases.TranslatePageMarkerBatchTest" \
    --tests "com.dualreader.app.domain.usecases.TranslatePageUseCaseAdditionalTest" \
    --tests "com.dualreader.app.domain.usecases.TranslatePageUseCaseCancellationTest" \
    --tests "com.dualreader.app.domain.usecases.TranslatePageUseCaseTest" \
    --tests "com.dualreader.app.domain.usecases.TranslationPipelineIntegrationTest" \
    --tests "com.dualreader.app.ui.navigation.NavHostCancellationTest"

run_batch 8 \
    --tests "com.dualreader.app.ui.navigation.NavHostTest" \
    --tests "com.dualreader.app.ui.PrivacyPolicyActivityTest" \
    --tests "com.dualreader.app.ui.screens.LibraryViewModelCancellationTest" \
    --tests "com.dualreader.app.ui.screens.LibraryViewModelErrorHandlingTest" \
    --tests "com.dualreader.app.ui.screens.LibraryViewModelExportTest" \
    --tests "com.dualreader.app.ui.screens.LibraryViewModelTest" \
    --tests "com.dualreader.app.ui.screens.ModelManagementViewModelCancellationTest" \
    --tests "com.dualreader.app.ui.screens.ModelManagementViewModelRaceConditionTest"

run_batch 8 \
    --tests "com.dualreader.app.ui.screens.ModelManagementViewModelTest" \
    --tests "com.dualreader.app.ui.screens.PaywallViewModelErrorHandlingTest" \
    --tests "com.dualreader.app.ui.screens.PaywallViewModelTest" \
    --tests "com.dualreader.app.ui.screens.PositionHistoryTest" \
    --tests "com.dualreader.app.ui.screens.ReaderColorsTest" \
    --tests "com.dualreader.app.ui.screens.ReaderViewModelAutoPaginateTest" \
    --tests "com.dualreader.app.ui.screens.ReaderViewModelCancellationTest" \
    --tests "com.dualreader.app.ui.screens.ReaderViewModelCloudUpgradeRaceConditionTest"

run_batch 8 \
    --tests "com.dualreader.app.ui.screens.ReaderViewModelCoverageTest" \
    --tests "com.dualreader.app.ui.screens.ReaderViewModelOnClearedCancellationTest" \
    --tests "com.dualreader.app.ui.screens.ReaderViewModelPersistenceTest" \
    --tests "com.dualreader.app.ui.screens.ReaderViewModelPositionTest" \
    --tests "com.dualreader.app.ui.screens.ReaderViewModelRaceConditionTest" \
    --tests "com.dualreader.app.ui.screens.ReaderViewModelSettingsUpdateTest" \
    --tests "com.dualreader.app.ui.screens.ReaderViewModelTranslationTest" \
    --tests "com.dualreader.app.ui.screens.ReaderViewModelTtsContinuousTest"

run_batch 8 \
    --tests "com.dualreader.app.ui.screens.ReaderViewModelWordJobTest" \
    --tests "com.dualreader.app.ui.screens.SentenceSplitterTest" \
    --tests "com.dualreader.app.ui.screens.SettingsViewModelErrorHandlingTest" \
    --tests "com.dualreader.app.ui.screens.SettingsViewModelTest" \
    --tests "com.dualreader.app.ui.screens.TranslationPipelineFixTest" \
    --tests "com.dualreader.app.ui.screens.UpdateSettingsRegressionTest" \
    --tests "com.dualreader.app.ui.screens.ViewModelChannelCleanupTest" \
    --tests "com.dualreader.app.ui.SplashPlayStoreTest"

run_batch 4 \
    --tests "com.dualreader.app.ui.theme.ThemeTest" \
    --tests "com.dualreader.app.util.AppLoggerClearTest" \
    --tests "com.dualreader.app.util.AppLoggerFailureTrackingTest" \
    --tests "com.dualreader.app.util.AppLoggerTest"


echo ""
echo "========================================="
echo "Batched Test Summary"
echo "========================================="
echo "Batches Passed: $PASSED/$BATCH_IDX"
echo "Batches Failed: $BATCHES_FAILED/$BATCH_IDX"
echo ""

if [ $BATCHES_FAILED -eq 0 ]; then
    echo "✅ All batches passed!"
    exit 0
else
    echo "❌ $BATCHES_FAILED batch(es) failed"
    exit 1
fi
