#!/usr/bin/env bash
# Batched test runner for OOM mitigation
# Problem: MockK/Kotlin reflection generates ~100+ MB metaspace per test class
#          running all classes in one JVM exceeds metaspace limits
# Solution: Split into batches with a fresh JVM per batch (auto-generated batches)
#
# Auto-generated by regenerate-test-batches.py from the test directory listing.
# Re-run that script after adding/removing test classes.

set -e
cd "$(dirname "$0")"

export JAVA_HOME="/c/Users/Svetlin/.jdks/temurin-21/jdk-21.0.11+10"
export TMPDIR="/tmp"

# Kill stale daemons holding file locks before starting
taskkill //F //IM java.exe 2>/dev/null || true
sleep 3

echo "========================================="
echo "Running full unit test suite in batches"
echo "========================================="

PASSED=0
FAILED=0
BATCHES_FAILED=0
BATCH_IDX=0

run_batch() {
    BATCH_IDX=$((BATCH_IDX+1))
    local count=$1; shift
    echo ""
    echo "[Batch $BATCH_IDX] $count test class(es)"
    echo "----------------------------"
    if timeout 900 ./gradlew :app:testDebugUnitTest --no-daemon \
        -Djava.io.tmpdir="$TMPDIR" \
        "$@"; then
        PASSED=$((PASSED+1))
    else
        FAILED=$((FAILED+1))
        BATCHES_FAILED=$((BATCHES_FAILED+1))
    fi
}

# Each batch: fresh JVM, bounded class count (OOM mitigation)
%_BATCHES%

echo ""
echo "========================================="
echo "Batched Test Summary"
echo "========================================="
echo "Batches Passed: $PASSED/$BATCH_IDX"
echo "Batches Failed: $BATCHES_FAILED/$BATCH_IDX"
echo ""

if [ $BATCHES_FAILED -eq 0 ]; then
    echo "✅ All batches passed!"
    exit 0
else
    echo "❌ $BATCHES_FAILED batch(es) failed"
    exit 1
fi
