// Mocks generated by Mockito 5.4.4 from annotations
// in simplenotes/test/services/search_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:simplenotes/models/category.dart' as _i3;
import 'package:simplenotes/models/note.dart' as _i2;
import 'package:simplenotes/services/storage_service.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeNote_0 extends _i1.SmartFake implements _i2.Note {
  _FakeNote_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCategory_1 extends _i1.SmartFake implements _i3.Category {
  _FakeCategory_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStorageException_2 extends _i1.SmartFake
    implements _i4.StorageException {
  _FakeStorageException_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [StorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageService extends _i1.Mock implements _i4.StorageService {
  MockStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<bool> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i2.Note> createNote(_i2.Note? note) => (super.noSuchMethod(
        Invocation.method(
          #createNote,
          [note],
        ),
        returnValue: _i5.Future<_i2.Note>.value(_FakeNote_0(
          this,
          Invocation.method(
            #createNote,
            [note],
          ),
        )),
      ) as _i5.Future<_i2.Note>);

  @override
  _i5.Future<_i2.Note?> getNote(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getNote,
          [id],
        ),
        returnValue: _i5.Future<_i2.Note?>.value(),
      ) as _i5.Future<_i2.Note?>);

  @override
  _i5.Future<List<_i2.Note>> getAllNotes() => (super.noSuchMethod(
        Invocation.method(
          #getAllNotes,
          [],
        ),
        returnValue: _i5.Future<List<_i2.Note>>.value(<_i2.Note>[]),
      ) as _i5.Future<List<_i2.Note>>);

  @override
  _i5.Future<List<_i2.Note>> getNotesByCategory(String? categoryId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNotesByCategory,
          [categoryId],
        ),
        returnValue: _i5.Future<List<_i2.Note>>.value(<_i2.Note>[]),
      ) as _i5.Future<List<_i2.Note>>);

  @override
  _i5.Future<_i2.Note> updateNote(_i2.Note? note) => (super.noSuchMethod(
        Invocation.method(
          #updateNote,
          [note],
        ),
        returnValue: _i5.Future<_i2.Note>.value(_FakeNote_0(
          this,
          Invocation.method(
            #updateNote,
            [note],
          ),
        )),
      ) as _i5.Future<_i2.Note>);

  @override
  _i5.Future<bool> deleteNote(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteNote,
          [id],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<int> deleteAllNotes() => (super.noSuchMethod(
        Invocation.method(
          #deleteAllNotes,
          [],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<_i3.Category> createCategory(_i3.Category? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #createCategory,
          [category],
        ),
        returnValue: _i5.Future<_i3.Category>.value(_FakeCategory_1(
          this,
          Invocation.method(
            #createCategory,
            [category],
          ),
        )),
      ) as _i5.Future<_i3.Category>);

  @override
  _i5.Future<_i3.Category?> getCategory(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getCategory,
          [id],
        ),
        returnValue: _i5.Future<_i3.Category?>.value(),
      ) as _i5.Future<_i3.Category?>);

  @override
  _i5.Future<List<_i3.Category>> getAllCategories() => (super.noSuchMethod(
        Invocation.method(
          #getAllCategories,
          [],
        ),
        returnValue: _i5.Future<List<_i3.Category>>.value(<_i3.Category>[]),
      ) as _i5.Future<List<_i3.Category>>);

  @override
  _i5.Future<_i3.Category> updateCategory(_i3.Category? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCategory,
          [category],
        ),
        returnValue: _i5.Future<_i3.Category>.value(_FakeCategory_1(
          this,
          Invocation.method(
            #updateCategory,
            [category],
          ),
        )),
      ) as _i5.Future<_i3.Category>);

  @override
  _i5.Future<bool> deleteCategory(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteCategory,
          [id],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<int> deleteAllCategories() => (super.noSuchMethod(
        Invocation.method(
          #deleteAllCategories,
          [],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i4.StorageException handleError(
    dynamic error,
    String? operation,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #handleError,
          [
            error,
            operation,
          ],
        ),
        returnValue: _FakeStorageException_2(
          this,
          Invocation.method(
            #handleError,
            [
              error,
              operation,
            ],
          ),
        ),
      ) as _i4.StorageException);
}
